services:
  liminal.example:
    image: liminal.example
    build:
      context: .
      dockerfile: Liminal.Example/Dockerfile

  homeschool.api:
    image: homeschool.api
    build:
      context: .
      dockerfile: HomeSchool.Api/Dockerfile
